id: rocketchat-misconfig
info:
  name: Rocket.Chat Misconfiguration Detection
  author: pwn
  severity: high
  description: Detects exposed Rocket.Chat instances with accessible sensitive endpoints, potentially vulnerable to unauthorized access.
  tags: rocketchat, misconfiguration

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/method.callAnon/sendForgotPasswordEmail"
      - "{{BaseURL}}:3000/api/v1/method.callAnon/sendForgotPasswordEmail"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Rocket.Chat"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "Rocket.Chat"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
