id: strapi-misconfig
info:
  name: Strapi Misconfiguration Detection
  author: pwn
  severity: high
  description: Detects exposed Strapi instances with accessible sensitive endpoints, potentially vulnerable to unauthorized access or information disclosure.
  tags: strapi, misconfiguration

http:
  - method: GET
    path:
      - "{{BaseURL}}/admin/strapiVersion"
      - "{{BaseURL}}/admin/plugins/users-permissions/auth/reset-password"
      - "{{BaseURL}}:1337/admin/strapiVersion"
      - "{{BaseURL}}:1337/admin/plugins/users-permissions/auth/reset-password"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Strapi"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "Strapi"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
