id: shiro-misconfig
info:
  name: Apache Shiro Misconfiguration Detection
  author: pwn
  severity: high
  description: Detects exposed Apache Shiro instances with accessible sensitive endpoints, potentially vulnerable to unauthorized access.
  tags: shiro, misconfiguration

http:
  - method: GET
    path:
      - "{{BaseURL}}/admin"
      - "{{BaseURL}}/xxx/..;/admin/"
      - "{{BaseURL}}:8080/admin"
      - "{{BaseURL}}:8080/xxx/..;/admin/"
    matchers-condition: or
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Shiro"
          - "Apache Shiro"
        part: body
        condition: or
        case-insensitive: true
      - type: word
        words:
          - "Shiro"
        part: body
        condition: or
        case-insensitive: true
      - type: status
        status:
          - 403
          - 401
    extractors:
      - type: regex
        name: matched_path
        part: request
        regex:
          - "https?://[^/]+(/.*)"
        group: 1
